name: Dependency Updates

on:
  schedule:
    - cron: '0 6 * * 1' # Run weekly on Monday at 6 AM
  workflow_dispatch: # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python 3.11
      run: uv python install 3.11

    - name: Update dependencies
      run: |
        uv sync --upgrade
        make install

    - name: Run tests after update
      run: |
        make test-quick

    - name: Run linting after update
      run: |
        make lint

    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: steps.changes.outputs.changed == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies"
        title: "chore: automated dependency updates"
        body: |
          Automated dependency updates
          
          - Updated Python dependencies to latest versions
          - All tests are passing
          - Code quality checks passed
        branch: dependency-updates
        delete-branch: true
