name: Performance Tests

on:
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2 AM
  workflow_dispatch:  # Allow manual triggering

jobs:
  performance-test:
    name: Performance Testing
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python 3.11
      run: uv python install 3.11

    - name: Install dependencies
      run: |
        make install
        uv add --group dev locust

    - name: Start API server
      run: |
        make start &
        sleep 10

    - name: Run performance tests
      run: |
        # Basic load test with locust
        uv run --group dev locust --headless --users 50 --spawn-rate 5 --run-time 2m --host http://localhost:9410 --locustfile tests/locustfile.py || true

    - name: Health check after load test
      run: |
        curl -f http://localhost:9410/health || exit 1
