name: Unit Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv sync --group dev

    - name: Run unit tests for models
      run: |
        PYTHONPATH=src uv run --group dev pytest tests/test_models.py -v --tb=short --cov=src.models --cov-report=xml:coverage-models.xml

    - name: Run unit tests for services  
      run: |
        PYTHONPATH=src uv run --group dev pytest tests/test_services.py -v --tb=short --cov=src.services --cov-report=xml:coverage-services.xml

    - name: Combine coverage reports
      run: |
        uv run --group dev coverage combine
        uv run --group dev coverage xml -o coverage-unit.xml
        uv run --group dev coverage report -m

    - name: Upload unit test coverage
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage-unit.xml
        flags: unittests
        name: unit-tests-${{ matrix.python-version }}
        fail_ci_if_error: false

  test-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python 3.11
      run: uv python install 3.11

    - name: Install dependencies
      run: |
        uv sync --group dev

    - name: Run API tests with coverage threshold
      run: |
        PYTHONPATH=src uv run --group dev pytest tests/test_api.py -v --cov=src.api --cov-fail-under=90 --cov-report=xml:coverage-api.xml

    - name: Upload API test coverage
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage-api.xml
        flags: apitests
        name: api-tests
        fail_ci_if_error: false

  test-integration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python 3.11
      run: uv python install 3.11

    - name: Install dependencies
      run: |
        uv sync --group dev

    - name: Run integration tests with coverage threshold
      run: |
        PYTHONPATH=src uv run --group dev pytest tests/test_integration.py -v --cov=src --cov-fail-under=60 --cov-report=xml:coverage-integration.xml

    - name: Upload integration test coverage
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage-integration.xml
        flags: integrationtests
        name: integration-tests
        fail_ci_if_error: false
